# Generated by Django 2.2.10 on 2020-02-04 07:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('code', models.CharField(max_length=30)),
                ('content1', wagtail.core.fields.RichTextField()),
                ('content2', wagtail.core.fields.StreamField([('demo1', wagtail.core.blocks.CharBlock(classname='full title')), ('demo2', wagtail.core.blocks.RichTextBlock()), ('demo3', wagtail.core.blocks.RawHTMLBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
